# Generated by Django 4.2.2 on 2023-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='destination_images/')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
